### ISSUE TITLE
miner_stats: cpu_temp.bat возвращает некорректную температуру

### ISSUE THREAD

**Issue by Aloki** [minershive/hiveos-win#2]
Получать температуру процессора через класс WMI _MSAcpi_ThermalZoneTemperature_ крайне ненадёжно. На моём железе Gigabyte GA-Z87N-WIFI и Intel Core i7-4770K свойство _CurrentTemperature_ имеет значение 3030, которое cpu_temp.bat "превращает" в 29.85, а в веб-морде оно вообще отображается как 0.02985°. По факту же процессор разогрет до 68°. Заметил, что агент Hive запускает Open Hardware Monitor, через который как раз и можно получать корректные показания различных сенсоров. Видимо в будущем так и будет, ну а пока отправлю этот багрепорт.

**Comment by Pasha49** [comment]
Спасибо за репорт! Этот метод получения температуры CPU был до добавления Open Hardware Monitor. Вы правы, данные температуры CPU будут скоро с него.

**Comment by Aloki** [comment]
Отлично, спасибо, ждём!
