### ISSUE TITLE
miner_stats: xmr-stak: баг в определении значения $gpus_disabled

### ISSUE THREAD

**Issue by Aloki** [minershive/hiveos-win#3]
Запускаю xmr-stak с ключами `--noAMD` `--noNVIDIA`. В этом случае майнер не пишет в лог ни "_WARNING: backend AMD (OpenCL) disabled_", ни "_WARNING: backend NVIDIA disabled_", и переменной _gpus_disabled_ остаётся присвоено пустое значение. В результате _jq_ сообщает о неверном синтаксисе (строка 250) и вместо статистики получаем _null_.

**Comment by Pasha49** [comment]
Добавляете эти параметры сами в скрипт запуска или в вебе хайва?
Если в вебе, то в поля "AMD config override" добавьте  
`"gpu_threads_conf" : [], "platform_index" : 0,`
и в "Nvidia config override" добавьте
`"gpu_threads_conf" : [],`
Если добавляли в скрипт, то куда именно? Покажите пожалуйста пример.

**Comment by Aloki** [comment]
Прощу прощения, мой косяк. Сразу полез в xmr-stak.sh дописывать в 11 строке ключи `--noAMD` и `--noNVIDIA`. Заполнил в вебе поля "AMD/Nvidia config override", и в логе майнера появились нужные строки, с переменной всё в порядке. Закрываю багрепорт.
